file_read = open("Mashle Plot.txt","r")
print(file_read.read())
file_read.close()
file_write=open("Mashle Plot.txt","w")
file_write.write("Hello")
file_write.close()
file=open("Mashle Plot.txt","a")
file.write("Hello")
file.write("It is my favourite show")
file.close()